spring.application.name=user-service
server.port=8080

spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://nadeemmohammed12346:bt5ejDPOluwYGjiE@project.ye2wcmq.mongodb.net/user_assessment_db}

jwt.secret.key=${JWT_SECRET:1VfGzUyotZgvj5jPEGCar8gWgpfEvbTai/tkvu3bk/Q=}
jwt.expiration.ms=86400000